[package]
name = "wgpu-bindutils"
description = "A WGPU wrapper to keep Bind Groups organized, type-safe and less error-prone"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
wgpu-bindutils-core = { path = "../wgpu-bindutils-core", version = "0.2.0" }
wgpu-bindutils-macro = { path = "../wgpu-bindutils-macro", version = "0.2.0" }