[package]
name = "wgpu-bindutils-core"
description = "Core structs, types and traits for the wgpu-bindutils crate"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bytemuck = { workspace = true }
wgpu = { workspace = true }
